export const promptExamples = [
  "Wong Kar-wai movies",
  "Movies that feel like a rainy Sunday afternoon",
  "Visually stunning sci-fi films",
  "Cozy Ghibli-esque films",
  "Cyberpunk anime from the 90s",
  "Mind-bending thrillers",
  "French New Wave classics",
  "Dark comedies with unexpected twists",
  "Movies with iconic soundtracks",
  "Slow-burn horror films",
  "Uplifting documentaries about nature",
  "Coming-of-age stories set in the summer",
  "Silent films that are still captivating",
  "Neo-noir mysteries",
  "Films featuring masterful cinematography",
  "Surreal comedies",
  "Movies about found families",
  "Epic space operas",
  "Indie films with quirky characters",
  "Thought-provoking philosophical movies",
  "Feel-good movies that aren't cheesy",
  "Atmospheric horror set in isolated locations",
  "Movies that explore the human condition",
  "Visually minimalist films",
  "Black and white films with high contrast",
  "Movies with non-linear narratives",
  "Films directed by women with a unique vision",
  "Heartwarming animated shorts",
  "Critically acclaimed international films",
  "Movies that make you question reality",
  "Cult classics you might have missed",
  "Satirical takes on modern society",
  "Films with strong female leads",
  "Historical dramas with accurate costumes",
  "Movies perfect for a movie night with friends",
  "Experimental films pushing boundaries",
  "Comfort movies to rewatch",
  "Movies that feel like a dream",
  "Westerns that subvert the genre",
  "Intense courtroom dramas",
  "Films about artists and their process",
  "Movies with unexpected plot twists",
  "Beautifully melancholic films",
  "Political thrillers that keep you guessing",
  "Time travel movies with clever rules",
  "Martial arts films with incredible choreography",
  "Movies exploring artificial intelligence",
  "Whimsical fantasy adventures",
  "Biopics about unconventional figures",
  "Films with a strong sense of place",
  "Mockumentaries that feel real",
  "Movies that are aesthetically pleasing",
  "Heist movies with intricate plans",
  "Post-apocalyptic survival stories",
  "Romantic comedies with genuine chemistry",
  "Films scored by Hans Zimmer",
  "Movies about the immigrant experience",
  "Animated films for adults",
  "Movies that feel like a warm hug",
  "Psychological dramas that stay with you",
  "Found footage horror that's actually scary",
  "Movies set entirely in one location",
  "Understated sci-fi films",
  "Documentaries about fascinating subcultures",
  "Films that capture the feeling of wanderlust",
  "Road trip movies with great soundtracks",
  "Movies based on classic literature",
  "Buddy cop movies with witty banter",
  "Revenge thrillers with satisfying payoffs",
  "Films celebrating music and musicians",
  "Movies with ambiguous endings",
  "Character studies of complex individuals",
  "Creature features with practical effects",
  "Movies that make you appreciate life",
  "Quentin Tarantino dialogue-heavy scenes",
  "Stanley Kubrick's visual masterpieces",
  "Wes Anderson's symmetrical worlds",
  "David Fincher's meticulous thrillers",
  "Christopher Nolan's complex narratives",
  "Greta Gerwig's nuanced female characters",
  "Denis Villeneuve's atmospheric sci-fi",
  "Park Chan-wook's stylish revenge tales",
  "Coen Brothers' quirky dark comedies",
  "Sofia Coppola's dreamy aesthetics",
  "Jordan Peele's social thrillers",
  "Movies that feel like a specific color palette",
  "Films exploring loneliness",
  "Movies perfect for a snowy day",
  "Stories about unlikely friendships",
  "Films set in bustling cities at night",
  "Movies about overcoming adversity",
  "Quiet, contemplative cinema",
  "Films that challenge societal norms",
  "Movies with unreliable narrators",
  "Visually inventive music videos (as films)",
  "Films that feel like poetry",
  "Movies shot on film with grainy texture",
  "Hidden gems from the 70s",
  "Arthouse horror recommendations",
  "Films that blend genres seamlessly",
  "Movies with award-winning production design",
  "80s nostalgia movies",
  "Satirical horror films",
  "Sports movies about underdogs",
  "Movies with stunning practical effects",
  "Romantic dramas that make you cry",
  "Films about the meaning of life",
  "Disaster movies with high stakes",
  "Movies with ensemble casts",
  "Inspiring teacher dramas",
  "Whodunnit mysteries with clever clues",
  "Films exploring grief and loss",
  "Movies set in space stations",
  "Social commentary disguised as genre films",
  "Animated musicals with catchy songs",
  "Films about espionage and spies",
  "Movies that celebrate food",
  "Alien invasion movies",
  "Supernatural romance stories",
  "Films focused on environmental themes",
  "Zombie movies with a unique twist",
  "Movies featuring philosophical robots",
  "Body horror films",
  "Coming-of-age stories with LGBTQ+ themes",
  "Musicals based on historical events",
  "Films that break the fourth wall",
  "World War II dramas from different perspectives",
  "Movies about childhood innocence",
  "Dystopian futures exploring societal control",
  "Films about journalists uncovering conspiracies",
  "Movies with parallel universes",
  "Psychological thrillers with unreliable memories",
  "Films exploring mental health challenges",
  "Superhero movies with deconstructions of the genre",
  "Movies about magic and illusion",
  "Films set during historical revolutions",
  "Oceanic adventure films",
  "Movies exploring the concept of identity",
  "Legal thrillers with moral ambiguity",
  "Films based on true crime stories",
  "Movies featuring sentient animals",
  "Gothic horror tales",
  "Family dramas spanning multiple generations",
  "Films about survival in the wilderness",
  "Satirical looks at the entertainment industry",
  "Movies exploring the impact of technology",
  "Films with minimalist dialogue",
  "Adaptations of Shakespearean plays",
  "Movies about con artists",
  "Fantasy films inspired by folklore",
  "Films set in alternate histories",
  "Horror comedies that balance scares and laughs",
  "Movies about existential dread",
  "Films exploring virtual reality",
  "Tearjerker animal movies",
  "Movies about political corruption",
  "Neo-Westerns set in modern times",
  "Films featuring anti-heroes you root for",
  "Sci-fi comedies",
  "Movies about the power of community",
  "Films exploring different cultures authentically",
  "Road movies across surreal landscapes",
  "Movies about scientific discovery",
  "Films that feel like a forgotten memory",
  "Paranormal investigation movies",
  "Films about the end of the world",
  "Masterpieces of silent comedy (Chaplin, Keaton)",
  "Italian Neorealism classics",
  "Samurai films by Akira Kurosawa",
  "German Expressionist cinema",
  "Stop-motion animation wonders",
  "Documentaries that changed public perception",
  "Films with iconic dance sequences",
  "Movies that inspired fashion trends",
  "Films based on graphic novels",
  "Underappreciated gems from the 90s indie scene",
  "Movies where the setting is a character",
  "Films tackling controversial topics head-on",
  "Movies with memorable villains",
  "Films about the creative struggle",
  "Movies that feel like autumn",
  "Feel-good sports documentaries",
  "Historical epics with grand battles",
  "Small-town dramas with big secrets",
  "Films that make you want to travel",
  "Movies about finding your purpose",
  "Abstract experimental films",
  "Films that play with cinematic form",
  "Movies that make you think for days",
  "Uplifting stories of human resilience",
  "Films with a distinct visual style",
  "Movies perfect for Halloween night",
  "Christmas movies that aren't overly sentimental",
  "Films celebrating friendship",
  "Movies that inspire creativity",
  "Indie sci-fi with big ideas, small budget",
  "Films with long, uninterrupted takes",
  "Documentaries about technological breakthroughs",
  "Films with striking color grading",
  "Dark fantasy movies",
  "Movies about secret societies",
  "Philosophical sci-fi exploring consciousness",
  "Films set in magical realism worlds",
  "Teen movies that aren't cringe-worthy",
  "Movies with powerful monologues",
  "Dogme 95 films",
  "Films that examine the nature of fame",
  "Atmospheric Nordic noir",
  "Films shot in unique aspect ratios",
  "Documentaries about social justice movements",
  "Animated films with painterly aesthetics",
  "Satirical takes on corporate culture",
  "Films exploring the complexities of family",
  "Movies with intricate world-building",
  "Cyberpunk thrillers",
  "Movies that blend documentary and fiction",
  "Surreal horror films",
  "Films about redemption",
  "Movies with low-key humor",
  "Understated ghost stories",
  "Films that capture the spirit of a city",
  "Movies about the power of music",
  "Existential comedies",
  "Films set in remote, beautiful landscapes",
  "Movies exploring the passage of time",
  "Character-driven dramas",
  "Films with unexpected musical numbers",
  "Movies that feel like a lucid dream",
  "Documentaries about wildlife conservation",
  "Films with metafictional elements",
  "Movies about the struggles of middle age",
  "Psychological horror without jump scares",
  "Films that celebrate individuality",
  "Movies with satisfyingly complex plots",
  "Sci-fi noir",
  "Films about finding beauty in the mundane",
  "Movies with minimalist scores",
  "Stories of survival against the odds",
  "Films that feel like a vintage postcard",
  "Documentaries profiling inspiring individuals",
  "Animated films based on mythology",
  "Satirical takes on political systems",
  "Films exploring memory and nostalgia",
  "Movies with non-professional actors",
  "Films about unlikely mentors",
  "Movies with ambiguous protagonists",
  "Subversive fairy tales",
  "Films examining the impact of social media",
  "Movies that are visually poetic",
  "Sci-fi body swap comedies",
  "Films about the pursuit of knowledge",
  "Movies with realistic depictions of relationships",
  "Heist comedies",
  "Films that feel like a hazy memory",
  "Documentaries about artistic movements",
  "Animated films using unique techniques",
  "Satirical takes on consumerism",
  "Films exploring cultural clashes",
  "Movies with claustrophobic settings",
  "Folk horror films",
  "Films about second chances",
  "Movies with deadpan humor",
  "Supernatural thrillers",
  "Films that capture the essence of youth",
  "Movies about the search for belonging",
  "Existential dramas",
  "Films set in libraries or bookstores",
  "Movies exploring the future of humanity",
  "Plot-driven thrillers",
  "Films with integrated animation/live-action",
  "Movies that feel like falling leaves",
  "Documentaries about scientific mysteries",
  "Films with unreliable perspectives",
  "Movies about midlife crises",
  "Psychological thrillers focusing on obsession",
  "Movies with cleverly hidden details",
  "Space Westerns",
  "Films about finding joy in simple things",
  "Movies with diegetic music focus",
  "Stories of overcoming societal expectations",
  "Films that feel like a painting",
  "Documentaries about historical events re-examined",
  "Animated films tackling mature themes",
  "Satirical takes on the media",
];

export function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}
